#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成1000+生活化語言學習題目"""

import json

# 德文題目基礎數據
german_data = [
    ("Ich möchte zum Frühstück ein Brötchen mit Butter und Marmelade essen.", "我想早餐吃塗黃油和果醬的麵包。"),
    ("Möchtest du ein Glas Orangensaft oder Milch zum Frühstück?", "你早餐要一杯柳橙汁還是牛奶？"),
    ("Der Kaffee ist noch zu heiß, ich warte noch ein bisschen.", "咖啡還太燙，我先等一下再喝。"),
    ("Zum Frühstück nehme ich gerne Müsli mit Obst und Joghurt.", "我早餐喜歡吃穀物麥片配水果和優格。"),
    ("Hast du das Brot aus dem Supermarkt oder vom Bäcker gekauft?", "你是從超市還是從麵包店買的麵包？"),
    ("Ich esse Spiegeleier mit Speck und Toast.", "我吃太陽蛋配培根和吐司。"),
    ("Magst du dein Ei weich gekocht oder hart gekocht?", "你喜歡吃軟煮蛋還是硬煮蛋？"),
    ("Zum Frühstück trinke ich immer grünen Tee.", "我早餐經常喝綠茶。"),
    ("Das Frühstück ist die wichtigste Mahlzeit des Tages.", "早餐是一天中最重要的餐點。"),
    ("Ich frühstücke nie, weil ich morgens keine Zeit habe.", "我早上沒時間，所以不吃早餐。"),
    ("Toast mit Avocado und Tomate ist sehr gesund.", "塗酪梨和番茄的吐司很健康。"),
    ("Pandabrot mit Nutella ist mein Favorit.", "塗花生醬的麵包是我的最愛。"),
    ("Ein Croissant mit heißem Kaffee ist perfekt.", "可頌和熱咖啡很搭。"),
    ("Ich mag Pancakes mit Ahornsirup zum Brunch.", "我喜歡早午餐吃楓糖漿鬆餅。"),
    ("Magst du Müsli mit Mandeln oder Haselnüssen?", "你喜歡吃杏仁還是榛果麥片？"),
    ("Was ist heute Mittag im Menü? Es sieht sehr lecker aus.", "今天午餐菜單是什麼？看起來很好吃。"),
    ("Ich nehme einen Salat mit Hähnchen und Öl-Essig-Dressing als Mittagessen.", "我午餐吃雞肉沙拉配油醋醬。"),
    ("Die Pasta schmeckt fantastisch, der Koch hat es perfekt gemacht.", "這義大利麵很好吃，廚師做得很完美。"),
    ("Kann ich noch einen Teller Suppe bekommen?", "我還能再要一盤湯嗎？"),
    ("Für Mittagessen will ich Fisch mit Gemüse und Kartoffeln.", "午餐我想吃魚配蔬菜和馬鈴薯。"),
    ("Ich esse Spaghetti mit Tomatensoße und Parmesan.", "我吃番茄醬義大利麵配帕瑪森起司。"),
    ("Das Hähnchen ist zu trocken, kann der Koch es nächstes Mal feuchter machen?", "雞肉太乾了，廚師下次能做得嫩一點嗎？"),
    ("Ich hätte gerne einen Burger mit Pommes.", "我想要一個漢堡配薯條。"),
    ("Der Reis ist heute besonders köstlich.", "今天的米飯特別好吃。"),
    ("Magst du scharf essen? Dieses Curry ist sehr würzig.", "你喜歡吃辣嗎？這咖哩很辛辣。"),
    ("Pizza mit Pilzen und Mozzarella ist mein Lieblingsgericht.", "蘑菇馬蘇里拉披薩是我的最愛。"),
    ("Ich esse Mittagessen nie, weil ich Diät halte.", "我不吃午餐，因為我在節食。"),
    ("Die Kartoffeln sind heute sehr mehlig und köstlich.", "今天的馬鈴薯很粉和好吃。"),
    ("Ich mag Sushi zum Mittagessen.", "我喜歡午餐吃壽司。"),
    ("Diese Cremesuppe ist absolut köstlich.", "這個奶油湯絕對很好吃。"),
    ("Heute Abend essen wir gegrilltes Hähnchen mit Reis und Brokkoli.", "今晚我們吃烤雞配米飯和綠花菜。"),
    ("Das Steak ist zu roh, kann der Kellner es noch mal auf den Grill legen?", "這牛排太生了，服務員能再把它放回烤架嗎？"),
    ("Magst du Würstchen oder lieber Fleischbällchen zum Abendessen?", "你晚餐喜歡吃香腸還是肉丸？"),
    ("Zum Nachtisch nehme ich Schokoladenkuchen mit Vanilleeis.", "甜點我要巧克力蛋糕配香草冰淇淋。"),
    ("Das Gemüse ist noch zu hart, können Sie es etwas länger kochen?", "蔬菜還太硬，你能再煮久一點嗎？"),
    ("Ich koche Suppe für das Abendessen.", "我晚餐煮湯。"),
    ("Rotkohl ist sehr lecker mit Kartoffeln.", "紫甘藍配馬鈴薯很好吃。"),
    ("Ich esse Fisch jeden Freitag zum Abendessen.", "我每個星期五晚餐吃魚。"),
    ("Das Rindersteak ist zu zäh, bitte machen Sie es zarter.", "牛排太硬了，請做得更嫩一些。"),
    ("Ich möchte eine leichte Mahlzeit zum Abendessen.", "我想要一份清淡的晚餐。"),
    ("Können Sie mir ein vegetarisches Gericht empfehlen?", "你能推薦一道素菜嗎？"),
    ("Das Schweinefleisch ist sehr zart heute.", "今天的豬肉很嫩。"),
    ("Ich mag Ente zum Abendessen, aber es ist sehr teuer.", "我喜歡晚餐吃鴨肉，但很貴。"),
    ("Die Kartoffelpuffer sind köstlich.", "馬鈴薯煎餅很好吃。"),
    ("Ich habe kein Appetit heute, ich esse nur einen leichten Salat.", "我今天沒有胃口，只吃清淡沙拉。"),
    ("Ich trinke jeden Morgen einen Kaffee.", "我每天早上喝一杯咖啡。"),
    ("Magst du Tee oder Kaffee lieber?", "你更喜歡喝茶還是咖啡？"),
    ("Ein Glas Wasser mit Zitrone, bitte.", "請給我一杯檸檬水。"),
    ("Ich trinke Wein zum Abendessen.", "我晚餐喝葡萄酒。"),
    ("Bier ist das beliebteste Getränk in Deutschland.", "啤酒是德國最受歡迎的飲品。"),
    ("Ich mag Orangensaft zum Frühstück.", "我早餐喜歡喝柳橙汁。"),
    ("Kann ich einen Espresso bekommen?", "我能要一杯濃咖啡嗎？"),
    ("Schwarzer Tee ohne Zucker, bitte.", "請給我無糖紅茶。"),
    ("Eine Tasse warme Schokolade ist perfekt für den Winter.", "一杯熱巧克力很適合冬天。"),
    ("Ich trinke viel Wasser, um gesund zu bleiben.", "我喝很多水來保持健康。"),
    ("Ich brauche Toilettenpapier. Wo kann ich es kaufen?", "我需要衛生紙。我在哪裡可以買到？"),
    ("Entschuldigung, wo ist die Toilette?", "不好意思，廁所在哪裡？"),
    ("Ich wasche meine Hände mit Seife.", "我用肥皂洗手。"),
    ("Mir fehlt die Zahnbürste, ich muss eine neue kaufen.", "我的牙刷丟了，我要買一把新的。"),
    ("Kann ich ein Handtuch haben?", "我能要一條毛巾嗎？"),
    ("Ich putze meine Zähne zweimal täglich.", "我每天刷牙兩次。"),
    ("Das Shampoo ist alle, ich kaufe morgen ein neues.", "洗髮精用完了，我明天買新的。"),
    ("Ich nehme ein warmes Bad zum Entspannen.", "我洗個溫水澡放鬆。"),
    ("Wo ist der Spiegel? Ich muss mein Haar kämmen.", "鏡子在哪裡？我要梳頭。"),
    ("Ich benutze Zahnseide jeden Abend.", "我每晚用牙線。"),
    ("Diese Soap ist sehr pflegend für die Haut.", "這個肥皂很滋潤皮膚。"),
    ("Ich dusche morgens, bevor ich zur Arbeit gehe.", "我上班前早上洗澡。"),
    ("Das Badezimmer ist kalt, können Sie die Heizung anmachen?", "浴室很冷，你能打開暖氣嗎？"),
    ("Ich trockne mein Haar mit dem Haartrockner.", "我用吹風機吹乾頭髮。"),
    ("Entschuldigung, die Toilette ist verstopft.", "不好意思，廁所堵塞了。"),
    ("Diese Hose passt mir nicht mehr, sie ist zu klein.", "這條褲子我穿不下了，太小了。"),
    ("Ich wasche die Wäsche bei 30 Grad.", "我用30度洗衣服。"),
    ("Das Hemd hat einen Fleck, ich versuche ihn zu entfernen.", "襯衫有個污漬，我試著去除。"),
    ("Ich bügele die Bluse, weil sie zerknittert ist.", "我熨女用襯衫，因為它很皺。"),
    ("Diese Jacke ist zu dick für den Sommer.", "這件夾克對夏天太厚了。"),
    ("Der Rock ist zu lang, ich muss ihn kürzer machen.", "裙子太長了，我要縮短。"),
    ("Ich mag diese Farbe nicht, kannst du mir ein anderes bringen?", "我不喜歡這個顏色，能給我另一件嗎？"),
    ("Diese Schuhe sind sehr bequem.", "這雙鞋很舒服。"),
    ("Ich trage lieber Baumwolle, weil sie natürlich ist.", "我更喜歡穿棉製品，因為它很天然。"),
    ("Der Anzug ist faltig geworden, ich bringe ihn zur Reinigung.", "西裝皺了，我送去乾洗。"),
    ("Ich wasche farbige Sachen separat.", "我單獨洗有顏色的衣服。"),
    ("Diese Bluse klebt an mir, weil sie nass ist.", "這件襯衫粘著我，因為它濕了。"),
    ("Ich kann diese Knöpfe nicht finden.", "我找不到這些扣子。"),
    ("Magst du Jeans oder lieber Anzughosen?", "你喜歡穿牛仔褲還是西裝褲？"),
    ("Ich muss neue Socken kaufen.", "我要買新襪子。"),
    ("Ich kehre das Wohnzimmer und wasche dann den Boden.", "我掃客廳，然後拖地。"),
    ("Der Müll ist voll, ich muss ihn leeren.", "垃圾桶滿了，我要倒垃圾。"),
    ("Ich wasche Geschirr nach dem Essen.", "吃完飯後我洗碗盤。"),
    ("Das Badezimmer ist schmutzig, ich putze es.", "浴室很髒，我要清潔它。"),
    ("Ich wechsle die Bettwäsche jede Woche.", "我每週換一次床單。"),
    ("Die Wäsche ist trocken, ich falte sie jetzt.", "衣服乾了，我現在摺疊。"),
    ("Ich staube die Möbel ab.", "我擦家具上的灰塵。"),
    ("Der Fenster ist schmutzig, ich wasche ihn.", "窗戶很髒，我要洗它。"),
    ("Ich sauge den Teppich.", "我吸地毯。"),
    ("Der Garten muss gepflegt werden.", "花園需要照料。"),
    ("Ich stelle die Küche auf den Kopf.", "我把廚房整理乾淨。"),
    ("Die Spüle riecht unangenehm, ich putze sie.", "水槽有異味，我要清潔。"),
    ("Ich wasche die Vorhänge einmal im Monat.", "我每個月洗一次窗簾。"),
    ("Der Spiegel ist beschlagen, ich wische ihn.", "鏡子起霧了，我擦一下。"),
    ("Ich mache das Haus sauber, bevor Gäste kommen.", "客人來之前我打掃房子。"),
    ("Wie viel kostet dieser Artikel?", "這個商品要多少錢？"),
    ("Kann ich mit Kreditkarte zahlen?", "我能用信用卡付款嗎？"),
    ("Das ist zu teuer, gibt es nicht etwas Billigeres?", "這太貴了，沒有更便宜的嗎？"),
    ("Ich habe einen Gutschein, kann ich ihn verwenden?", "我有張禮券，能用嗎？"),
    ("Können Sie mir eine Quittung geben?", "你能給我收據嗎？"),
    ("Ich suche nach einem roten Kleid.", "我找一件紅色洋裝。"),
    ("Haben Sie diesen Artikel in Größe M?", "你們有M號的這個商品嗎？"),
    ("Das Angebot läuft nur heute.", "這個優惠只到今天。"),
    ("Ich möchte diesen Artikel umtauschen.", "我想換這個商品。"),
    ("Gibt es eine Rückgabegarantie?", "有退貨保證嗎？"),
    ("Das Produkt ist fehlerhaft, können Sie mir ein neues geben?", "產品有缺陷，能給我新的嗎？"),
    ("Ich kaufe gerne online ein.", "我喜歡網上購物。"),
    ("Die Versandkosten sind zu hoch.", "運費太高了。"),
    ("Kann ich in Raten zahlen?", "我能分期付款嗎？"),
    ("Gibt es einen Studentenrabatt?", "有學生折扣嗎？"),
    ("Wo ist die nächste Bushaltestelle?", "最近的公車站在哪裡？"),
    ("Eine Fahrkarte zum Flughafen, bitte.", "請給我一張到機場的票。"),
    ("Mein Auto braucht Benzin.", "我的車需要加油。"),
    ("Der Zug hat Verspätung.", "火車晚點了。"),
    ("Ich brauche ein Taxi.", "我需要一輛計程車。"),
    ("Wie komme ich zum Bahnhof?", "我怎麼去火車站？"),
    ("Kann ich hier parken?", "我能停車嗎？"),
    ("Die Autobahn ist heute sehr voll.", "今天的高速公路很擁擠。"),
    ("Ich möchte eine Monatskarte kaufen.", "我想買月票。"),
    ("Wie lange dauert die Fahrt?", "車程要多久？"),
    ("Ich bin krank und möchte einen Termin beim Arzt machen.", "我生病了，想預約看醫生。"),
    ("Ich habe Kopfschmerzen, kann ich eine Tablette haben?", "我頭痛，能給我一顆藥嗎？"),
    ("Der Hals tut mir sehr weh.", "我的喉嚨很痛。"),
    ("Ich brauche einen Verband für die Wunde.", "我需要繃帶包紮傷口。"),
    ("Ich mache täglich Sport.", "我每天運動。"),
    ("Ich bin allergisch gegen Erdnüsse.", "我對花生過敏。"),
    ("Ich nehme Medikamente gegen Bluthochdruck.", "我吃血壓藥。"),
    ("Die Grippe ist schlimm in dieser Saison.", "這個季節流感很嚴重。"),
    ("Ich war beim Zahnarzt, um meine Zähne zu putzen.", "我去牙醫診所洗牙。"),
    ("Ich bin diabetisch, daher esse ich keinen Zucker.", "我是糖尿病患者，所以不吃糖。"),
    ("Wie heißt du?", "你叫什麼名字？"),
    ("Guten Tag, wie geht es dir?", "你好，你怎麼樣？"),
    ("Danke, mir geht es gut. Und dir?", "謝謝，我很好。你呢？"),
    ("Tschüss! Bis dann!", "再見！待會見！"),
    ("Schön, dich zu sehen!", "很高興見到你！"),
    ("Wie ist das Wetter heute?", "今天天氣怎麼樣？"),
    ("Es regnet heute.", "今天下雨。"),
    ("Die Sonne scheint sehr hell.", "太陽很亮。"),
    ("Es ist sehr kalt heute.", "今天很冷。"),
    ("Es ist sehr heiß heute.", "今天很熱。"),
    ("Ich mag diesen Tag sehr.", "我很喜歡今天。"),
    ("Was machst du morgen?", "你明天做什麼？"),
    ("Ich bin viel beschäftigt.", "我很忙。"),
    ("Hast du Zeit für mich?", "你有時間見我嗎？"),
    ("Ich bin bereit zu helfen.", "我準備好幫忙。"),
    ("Das ist eine gute Idee.", "那是個好主意。"),
    ("Das ist nicht gut.", "那不好。"),
    ("Ich bin einverstanden.", "我同意。"),
    ("Ich bin nicht einverstanden.", "我不同意。"),
    ("Das ist sehr wichtig.", "那很重要。"),
    ("Das ist egal.", "那無所謂。"),
    ("Was ist dein Hobby?", "你的愛好是什麼？"),
    ("Ich mag Musik hören.", "我喜歡聽音樂。"),
    ("Ich mag lesen.", "我喜歡看書。"),
    ("Ich mag Filme sehen.", "我喜歡看電影。"),
    ("Ich mag Spiele spielen.", "我喜歡玩遊戲。"),
    ("Hast du einen Hund?", "你有狗嗎？"),
    ("Hast du eine Katze?", "你有貓嗎？"),
    ("Ich habe zwei Bruder.", "我有兩個哥哥。"),
    ("Ich habe eine Schwester.", "我有一個妹妹。"),
    ("Meine Mutter ist nett.", "我媽媽很好。"),
    ("Mein Vater arbeitet viel.", "我爸爸工作很多。"),
    ("Wo lebst du?", "你住在哪裡？"),
    ("Ich lebe in der Stadt.", "我住在城市。"),
    ("Ich lebe auf dem Land.", "我住在鄉下。"),
    ("Ich lebe in einem Dorf.", "我住在村子裡。"),
    ("Ich arbeite in einem Büro.", "我在辦公室工作。"),
    ("Ich bin Student.", "我是學生。"),
    ("Ich bin Lehrer.", "我是老師。"),
    ("Ich bin Arzt.", "我是醫生。"),
    ("Ich bin Krankenschwester.", "我是護士。"),
    ("Ich bin Ingenieur.", "我是工程師。"),
    ("Was ist dein Traum?", "你的夢想是什麼？"),
    ("Ich möchte reisen.", "我想旅行。"),
    ("Ich möchte Geld verdienen.", "我想賺錢。"),
    ("Ich möchte eine Familie haben.", "我想有一個家庭。"),
    ("Ich bin nicht verheiratet.", "我沒有結婚。"),
    ("Ich bin verheiratet.", "我已經結婚了。"),
    ("Ich bin geschieden.", "我已經離婚了。"),
    ("Ich bin Single.", "我是單身。"),
    ("Was isst du gerne?", "你喜歡吃什麼？"),
    ("Ich mag Obst.", "我喜歡水果。"),
    ("Ich mag Gemüse.", "我喜歡蔬菜。"),
    ("Ich mag Fleisch.", "我喜歡肉。"),
    ("Ich mag Fisch.", "我喜歡魚。"),
    ("Ich bin Vegetarier.", "我是素食者。"),
    ("Ich bin Veganer.", "我是純素者。"),
    ("Wie viele Sprachen sprichst du?", "你會說多少種語言？"),
    ("Ich spreche drei Sprachen.", "我會說三種語言。"),
    ("Deutsch ist schwer.", "德語很難。"),
    ("Englisch ist leicht.", "英語很簡單。"),
    ("Ich möchte besser Deutsch sprechen.", "我想說得更好的德語。"),
    ("Ich lerne jeden Tag Deutsch.", "我每天學德語。"),
    ("Du sprichst sehr gut Deutsch.", "你德語說得很好。"),
    ("Ich verstehe dich nicht.", "我不懂你。"),
    ("Kannst du bitte langsamer sprechen?", "能請你慢一點講嗎？"),
    ("Kannst du bitte das wiederholen?", "能請你重複一遍嗎？"),
    ("Was bedeutet dieses Wort?", "這個單字是什麼意思？"),
    ("Wie spricht man das aus?", "怎麼發音？"),
    ("Schreib das bitte auf!", "請把它寫下來！"),
    ("Zeig mir ein Beispiel.", "給我一個例子。"),
    ("Das macht Sinn.", "那很合理。"),
    ("Das ergibt keinen Sinn.", "那沒有意義。"),
    ("Ich verstehe jetzt.", "我現在懂了。"),
    ("Ich bin verwirrt.", "我困惑了。"),
    ("Kannst du mir helfen?", "你能幫我嗎？"),
    ("Natürlich, kein Problem.", "當然可以，沒問題。"),
    ("Das ist kein Problem.", "那不是問題。"),
    ("Das ist ein großes Problem.", "那是個大問題。"),
    ("Ich habe ein Problem.", "我有個問題。"),
    ("Ich weiß nicht.", "我不知道。"),
    ("Ich bin mir nicht sicher.", "我不確定。"),
    ("Vielleicht.", "也許。"),
    ("Ich glaube, ja.", "我想是。"),
    ("Ich glaube, nein.", "我想不是。"),
    ("Das ist wahr.", "那是真的。"),
    ("Das ist falsch.", "那是假的。"),
    ("Das ist möglich.", "那是可能的。"),
    ("Das ist unmöglich.", "那是不可能的。"),
    ("Es ist zu spät.", "太晚了。"),
    ("Es ist noch früh.", "還很早。"),
    ("Es ist genau die richtige Zeit.", "正好是時候。"),
    ("Wann kommst du?", "你什麼時候來？"),
    ("Ich komme um drei Uhr.", "我三點來。"),
    ("Ich komme morgen.", "我明天來。"),
    ("Ich komme nächste Woche.", "我下週來。"),
    ("Ich bin dir schuldig.", "我欠你一個人情。"),
    ("Kein Problem, wir sind Freunde.", "沒關係，我們是朋友。"),
    ("Du bist mein bester Freund.", "你是我最好的朋友。"),
    ("Ich vermisse dich.", "我想你。"),
    ("Ich freue mich auf dich zu sehen.", "我期待見到你。"),
    ("Das war schön.", "那很好。"),
    ("Das war schrecklich.", "那很糟糕。"),
    ("Das war lustig.", "那很有趣。"),
    ("Das war langweilig.", "那很無聊。"),
    ("Das war interessant.", "那很有趣。"),
    ("Das war faszinierend.", "那很迷人。"),
    ("Glückwunsch!", "恭喜！"),
    ("Herzlichen Glückwunsch zum Geburtstag!", "生日快樂！"),
    ("Alles Gute zum Jahrestag!", "周年快樂！"),
    ("Frohe Weihnachten!", "聖誕快樂！"),
    ("Frohes neues Jahr!", "新年快樂！"),
    ("Alles Gute!", "一切順利！"),
    ("Viel Erfolg!", "祝你成功！"),
    ("Viel Spaß!", "玩得開心！"),
    ("Gute Reise!", "旅途愉快！"),
    ("Gute Nacht!", "晚安！"),
    ("Schlaf gut!", "睡得好！"),
    ("Süße Träume!", "做美夢！"),
    ("Pass auf dich auf!", "照顧好自己！"),
    ("Mach's gut!", "保重！"),
    ("Viel Glück!", "祝你好運！"),
    ("Ich liebe dich.", "我愛你。"),
    ("Du bist wunderschön.", "你很漂亮。"),
    ("Du bist sehr klug.", "你很聰明。"),
    ("Du bist sehr nett.", "你很好。"),
    ("Du bist sehr lustig.", "你很有趣。"),
    ("Ich mag dich.", "我喜歡你。"),
    ("Du tust mir leid.", "我為你難過。"),
    ("Ich bin stolz auf dich.", "我為你感到驕傲。"),
    ("Ich vertraue dir.", "我信任你。"),
    ("Du kannst mir vertrauen.", "你可以信任我。"),
    ("Das ist ein Geheimnis.", "那是個秘密。"),
    ("Ich kann es dir nicht sagen.", "我不能告訴你。"),
    ("Sag mir die Wahrheit.", "告訴我真相。"),
    ("Lüg mich nicht an.", "別騙我。"),
    ("Das ist deine Schuld.", "那是你的錯。"),
    ("Das ist nicht meine Schuld.", "那不是我的錯。"),
    ("Entschuldigung, es tut mir leid.", "對不起，我很抱歉。"),
    ("Es ist in Ordnung, kein Problem.", "沒關係，沒問題。"),
    ("Ich vergebe dir.", "我原諒你。"),
    ("Ich kann dir nicht vergeben.", "我不能原諒你。"),
    ("Wir müssen reden.", "我們需要談話。"),
    ("Ich bin angry.", "我生氣了。"),
    ("Ich bin traurig.", "我難過。"),
    ("Ich bin glücklich.", "我很高興。"),
    ("Ich bin nervös.", "我很緊張。"),
    ("Ich bin ängstlich.", "我害怕。"),
    ("Ich bin mutig.", "我很勇敢。"),
    ("Ich bin fröhlich.", "我很快樂。"),
    ("Ich bin deprimiert.", "我很沮喪。"),
    ("Ich bin verwirrt.", "我很困惑。"),
    ("Ich bin überrascht.", "我很驚訝。"),
    ("Ich bin enttäuscht.", "我很失望。"),
    ("Ich bin neugierig.", "我很好奇。"),
    ("Ich bin vergnügt.", "我很愉快。"),
    ("Ich bin genervt.", "我很煩。"),
    ("Das ist großartig!", "那太棒了！"),
    ("Das ist furchtbar!", "那太可怕了！"),
    ("Das ist fantastisch!", "那太棒了！"),
    ("Das ist wunderbar!", "那太美妙了！"),
    ("Das ist ausgezeichnet!", "那很優秀！"),
    ("Das ist OK.", "那還可以。"),
    ("Das ist so lala.", "那一般般。"),
    ("Das ist mittelmäßig.", "那還算中等。"),
    ("Das ist nicht gut.", "那不好。"),
    ("Das ist schrecklich.", "那太糟糕了。"),
]

# 日文題目基礎數據
japanese_data = [
    ("朝食にトーストとコーヒーをいただきます。", "早餐我吃吐司和咖啡。"),
    ("卵焼きは美味しくて、毎日食べたいです。", "蛋卷很好吃，我每天都想吃。"),
    ("ご飯とみそ汁と漬物で、朝食をします。", "我早餐吃米飯、味噌湯和醃菜。"),
    ("牛乳をコップに入れてください。", "請把牛奶倒進杯子裡。"),
    ("パンはバターとジャムを塗って食べます。", "我在麵包上塗黃油和果醬後吃。"),
    ("納豆ご飯を毎朝食べます。", "我每天早上吃納豆飯。"),
    ("朝食は和食が好きです。", "我喜歡早餐吃和食。"),
    ("シリアルと牛乳で朝食を済ませます。", "我用穀物麥片和牛奶吃早餐。"),
    ("朝食後、学校に行きます。", "早餐後我去上學。"),
    ("朝食を食べないで、仕事に行く人が多い。", "許多人不吃早餐就去上班。"),
    ("昼食はラーメンと餃子を食べたいです。", "午餐我想吃拉麵和餃子。"),
    ("寿司はたくさんネタが入っていて、とても美味しい。", "壽司有很多餡料，很好吃。"),
    ("この天丼の天ぷらは揚げたてで、最高です。", "這個天丼的天婦羅是剛炸的，最棒。"),
    ("蕎麦はつゆに浸して食べるのが好きです。", "我喜歡把蕎麥麵浸在湯汁裡吃。"),
    ("定食は定食は御飯、味噌汁、おかずが付いてくる。", "套餐通常包括米飯、味噌湯和配菜。"),
    ("カツ丼は揚げたての豚カツが最高です。", "炸豬排蓋飯的炸豬排最好吃。"),
    ("そばうどんとどちらが好きですか？", "蕎麥麵和烏龍麵你更喜歡哪一個？"),
    ("弁当を持って、公園で食べましょう。", "我們帶便當到公園吃。"),
    ("カレーライスは簡単で美味しい。", "咖哩飯簡單又好吃。"),
    ("焼き魚と野菜で、健康的な昼食です。", "烤魚和蔬菜是健康的午餐。"),
    ("夜ご飯には焼き魚を作ります。", "晚餐我做烤魚。"),
    ("すき焼きはたくさん野菜と肉が入っています。", "壽喜燒裡有很多蔬菜和肉。"),
    ("カレーライスは国民食と言えます。", "咖哩飯可以說是國民食物。"),
    ("親子丼はとても栄養がありますね。", "親子丼很有營養。"),
    ("夜食の時は、塩辛いものより軽いものが好きです。", "晚餐時我喜歡清淡的食物勝過鹹的。"),
    ("味噌汁は毎晩作ります。", "我每晚都做味噌湯。"),
    ("野菜をいっぱい食べて、健康です。", "吃很多蔬菜很健康。"),
    ("ステーキは久しぶりに食べたい。", "好久沒吃牛排了。"),
    ("天ぷらは油っぽいけど、美味しい。", "天婦羅油膩但很好吃。"),
    ("春キャベツの炒め物は最高です。", "春天高麗菜炒菜最棒。"),
    ("毎朝コーヒーを飲みます。", "我每天早上喝咖啡。"),
    ("紅茶はミルクを入れて飲みます。", "我在紅茶裡加牛奶。"),
    ("冷たい水が飲みたいです。", "我想喝冷水。"),
    ("日本茶は好きですか？", "你喜歡喝日本茶嗎？"),
    ("ビールはドイツが有名です。", "啤酒以德國最有名。"),
    ("オレンジジュースは朝食に最適です。", "柳橙汁是早餐的最佳選擇。"),
    ("エスプレッソはイタリアンコーヒーです。", "濃咖啡是義大利咖啡。"),
    ("緑茶は砂糖なしで飲みます。", "我不加糖喝綠茶。"),
    ("ホットチョコレートは冬に美味しい。", "熱巧克力在冬天很好喝。"),
    ("水をたくさん飲んで、健康です。", "喝很多水很健康。"),
    ("トイレットペーパーを買う必要があります。", "我需要買衛生紙。"),
    ("すみません、トイレはどこですか？", "不好意思，廁所在哪裡？"),
    ("シャンプーは髪に優しいものを選びました。", "我選了溫和的洗髮精。"),
    ("お風呂の時間は、一日で一番リラックスできる時間です。", "洗澡時間是一天中最放鬆的時刻。"),
    ("歯磨きは毎日二回行っています。", "我每天刷牙兩次。"),
    ("タオルで体を拭きます。", "我用毛巾擦身體。"),
    ("石鹸で手を洗います。", "我用肥皂洗手。"),
    ("歯ブラシを新しいのに変えました。", "我把牙刷換成新的。"),
    ("入浴剤を使って、気持ちいいです。", "用浴鹽很舒服。"),
    ("鏡に曇りが出ました。", "鏡子起霧了。"),
    ("このシャツは洗濯すると、少し小さくなってしまいました。", "這件襯衫洗過後變小了。"),
    ("衣類は30度の水で優しく洗います。", "衣服用30度的溫水輕輕洗。"),
    ("このスカートにシミが付いて、困っています。", "這條裙子沾上污漬，我很困擾。"),
    ("アイロンをかけて、シワを取ります。", "我熨衣服來去除皺紋。"),
    ("冬のコートは厚いですから、クリーニングに出します。", "冬天的大衣很厚，我送去乾洗。"),
    ("色物と白物は別々に洗います。", "有顏色的衣服和白衣服要分開洗。"),
    ("靴下をなくしました。", "我丟了襪子。"),
    ("ズボンのファスナーが壊れました。", "褲子的拉鏈壞了。"),
    ("セーターは毛玉ができました。", "毛衣起毛球了。"),
    ("洋服を整理して、捨てるものを見つけました。", "整理衣服時發現一些可以丟掉的。"),
    ("掃除の時間は、毎週日曜日にしています。", "我每個星期天做家務。"),
    ("ゴミを出す日は、火曜日と金曜日です。", "倒垃圾的日期是星期二和星期五。"),
    ("食器洗いは時間がかかりますが、必要です。", "洗碗盤耗時但必要。"),
    ("浴室の掃除は、毎日少しずつ行っています。", "我每天花一點時間清潔浴室。"),
    ("布団はたたいて、天日で干します。", "我拍打被子後放在陽光下曬。"),
    ("部屋を掃くとホコリが出ます。", "掃房間時會出現灰塵。"),
    ("窓ガラスを綺麗に拭きました。", "我把窗玻璃擦乾淨了。"),
    ("台所が汚れたので、清掃しました。", "廚房很髒，我清潔了。"),
    ("洗濯物を干して、明朝に取り入れます。", "我掛衣服，明早收進去。"),
    ("家の中を片付けるのは大変です。", "打掃房子很費力。"),
    ("この商品は幾らですか？安く買えますか？", "這個商品要多少錢？能便宜一點嗎？"),
    ("クレジットカードで払えますか、それとも現金だけですか？", "能用信用卡付款，還是只能付現？"),
    ("これは少し高いですが、品質がいいですね。", "這個有點貴，但品質很好。"),
    ("クーポンを持っています、使えますか？", "我有張折扣券，能用嗎？"),
    ("レシートをください。返品する時に必要です。", "請給我收據。我退貨時需要。"),
    ("駅はどこですか。電車に乗りたいです。", "車站在哪裡？我想搭電車。"),
    ("羽田空港行の電車の切符をください。", "請給我到羽田機場的電車票。"),
    ("このタクシーはいくらですか？", "這輛計程車要多少錢？"),
    ("電車は遅れています。到着は何時ですか？", "電車晚點了。什麼時候到達？"),
    ("自分の車にガソリンが必要です。ガソリンスタンドはどこですか？", "我的車需要加油。加油站在哪裡？"),
    ("おはようございます。今日はお天気がいいですね。", "早安。今天天氣很好。"),
    ("すみません、お名前は何ですか？", "不好意思，請問你叫什麼名字？"),
    ("ご協力ありがとうございます。お手伝いいただき感謝します。", "謝謝你的幫忙。感謝你的協助。"),
    ("すみません、手伝っていただけますか？", "不好意思，你能幫我嗎？"),
    ("さようなら。また明日。", "再見。明天見。"),
    ("具合が悪いので、医者の予約を取りたいです。", "我感覺不舒服，想預約看醫生。"),
    ("頭が痛いので、頭痛薬をください。", "我頭痛，請給我止痛藥。"),
    ("喉が痛いです。もしかして風邪かもしれません。", "我喉嚨痛。也許我感冒了。"),
    ("怪我をしたので、ばんそうこうが必要です。", "我受傷了，需要繃帶。"),
    ("毎日運動することが、健康を保つコツです。", "每天運動是保持健康的秘訣。"),
    ("あなたの名前は何ですか？", "你叫什麼名字？"),
    ("こんにちは。元気ですか？", "你好。你怎麼樣？"),
    ("ありがとうございます。元気です。あなたは？", "謝謝，我很好。你呢？"),
    ("さようなら。また今度！", "再見。下次見！"),
    ("お会いできて嬉しいです。", "很高興見到你。"),
    ("今日の天気はどうですか？", "今天天氣怎麼樣？"),
    ("今日は雨が降っています。", "今天下雨。"),
    ("太陽が輝いています。", "太陽很亮。"),
    ("今日はとても寒いです。", "今天很冷。"),
    ("今日はとても暑いです。", "今天很熱。"),
    ("この日が大好きです。", "我很喜歡今天。"),
    ("明日は何をしますか？", "你明天做什麼？"),
    ("とても忙しいです。", "我很忙。"),
    ("私の時間はありますか？", "你有時間見我嗎？"),
    ("喜んで手伝います。", "我很樂意幫忙。"),
    ("これはいいアイデアです。", "那是個好主意。"),
    ("これはよくありません。", "那不好。"),
    ("私は同意します。", "我同意。"),
    ("私は同意しません。", "我不同意。"),
    ("これはとても重要です。", "那很重要。"),
    ("それは問題ではありません。", "那無所謂。"),
    ("あなたの趣味は何ですか？", "你的愛好是什麼？"),
    ("私は音楽を聴くのが好きです。", "我喜歡聽音樂。"),
    ("私は読書が好きです。", "我喜歡看書。"),
    ("私は映画を見るのが好きです。", "我喜歡看電影。"),
    ("私はゲームをするのが好きです。", "我喜歡玩遊戲。"),
    ("犬を飼っていますか？", "你有狗嗎？"),
    ("猫を飼っていますか？", "你有貓嗎？"),
    ("私は兄が二人います。", "我有兩個哥哥。"),
    ("私は妹がいます。", "我有一個妹妹。"),
    ("私の母はいい人です。", "我媽媽很好。"),
    ("父は仕事をいっぱいしています。", "我爸爸工作很多。"),
    ("どこに住んでいますか？", "你住在哪裡？"),
    ("私は町に住んでいます。", "我住在城市。"),
    ("私は田舎に住んでいます。", "我住在鄉下。"),
    ("私は村に住んでいます。", "我住在村子裡。"),
    ("私はオフィスで働いています。", "我在辦公室工作。"),
    ("私は学生です。", "我是學生。"),
    ("私は教師です。", "我是老師。"),
    ("私は医者です。", "我是醫生。"),
    ("私は看護師です。", "我是護士。"),
    ("私はエンジニアです。", "我是工程師。"),
    ("あなたの夢は何ですか？", "你的夢想是什麼？"),
    ("私は旅行したいです。", "我想旅行。"),
    ("私はお金を稼ぎたいです。", "我想賺錢。"),
    ("私は家族を持ちたいです。", "我想有一個家庭。"),
    ("私は結婚していません。", "我沒有結婚。"),
    ("私は結婚しています。", "我已經結婚了。"),
    ("私は離婚しています。", "我已經離婚了。"),
    ("私はシングルです。", "我是單身。"),
    ("何を食べるのが好きですか？", "你喜歡吃什麼？"),
    ("私は果物が好きです。", "我喜歡水果。"),
    ("私は野菜が好きです。", "我喜歡蔬菜。"),
    ("私は肉が好きです。", "我喜歡肉。"),
    ("私は魚が好きです。", "我喜歡魚。"),
    ("私はベジタリアンです。", "我是素食者。"),
    ("私はビーガンです。", "我是純素者。"),
    ("何言語を話しますか？", "你會說多少種語言？"),
    ("私は三言語を話します。", "我會說三種語言。"),
    ("日本語は難しいです。", "日語很難。"),
    ("英語は簡単です。", "英語很簡單。"),
    ("私はもっと良い日本語を話したいです。", "我想說得更好的日語。"),
    ("私は毎日日本語を勉強しています。", "我每天學日語。"),
    ("あなたは日本語をとても上手に話しています。", "你日語說得很好。"),
    ("私はあなたを理解していません。", "我不懂你。"),
    ("ゆっくり話してくれますか？", "能請你慢一點講嗎？"),
    ("もう一度言ってくれますか？", "能請你重複一遍嗎？"),
    ("この単語はどういう意味ですか？", "這個單字是什麼意思？"),
    ("どう発音しますか？", "怎麼發音？"),
    ("これを書いてください。", "請把它寫下來。"),
    ("例を示してください。", "給我一個例子。"),
    ("それは理にかなっています。", "那很合理。"),
    ("それは意味がありません。", "那沒有意義。"),
    ("今わかります。", "我現在懂了。"),
    ("私は混乱しています。", "我困惑了。"),
    ("手伝ってくれますか？", "你能幫我嗎？"),
    ("もちろん、問題ありません。", "當然可以，沒問題。"),
    ("それは問題ではありません。", "那不是問題。"),
    ("それは大きな問題です。", "那是個大問題。"),
    ("私は問題があります。", "我有個問題。"),
    ("私はわかりません。", "我不知道。"),
    ("私は確実ではありません。", "我不確定。"),
    ("多分。", "也許。"),
    ("そう思います。", "我想是。"),
    ("そう思いません。", "我想不是。"),
    ("それは本当です。", "那是真的。"),
    ("それは嘘です。", "那是假的。"),
    ("それは可能です。", "那是可能的。"),
    ("それは不可能です。", "那是不可能的。"),
    ("遅すぎます。", "太晚了。"),
    ("まだ早いです。", "還很早。"),
    ("ちょうど良い時間です。", "正好是時候。"),
    ("いつ来ますか？", "你什麼時候來？"),
    ("私は3時に来ます。", "我三點來。"),
    ("私は明日来ます。", "我明天來。"),
    ("来週に来ます。", "我下週來。"),
    ("私はあなたに借りがあります。", "我欠你一個人情。"),
    ("問題ありません。私たちは友達です。", "沒關係，我們是朋友。"),
    ("あなたは私の親友です。", "你是我最好的朋友。"),
    ("あなたが恋しいです。", "我想你。"),
    ("あなたに会うのを楽しみにしています。", "我期待見到你。"),
    ("それは素晴らしかったです。", "那很好。"),
    ("それはひどかったです。", "那很糟糕。"),
    ("それは楽しかったです。", "那很有趣。"),
    ("それは退屈でした。", "那很無聊。"),
    ("それは興味深かったです。", "那很有趣。"),
    ("それは魅惑的でした。", "那很迷人。"),
    ("おめでとうございます。", "恭喜！"),
    ("お誕生日おめでとうございます。", "生日快樂！"),
    ("記念日おめでとうございます。", "周年快樂！"),
    ("メリークリスマス。", "聖誕快樂！"),
    ("新年おめでとうございます。", "新年快樂！"),
    ("幸運を祈っています。", "一切順利！"),
    ("成功を祈っています。", "祝你成功！"),
    ("楽しんでください。", "玩得開心！"),
    ("良い旅を。", "旅途愉快！"),
    ("おやすみなさい。", "晚安！"),
    ("よく寝てください。", "睡得好！"),
    ("いい夢を見てね。", "做美夢！"),
    ("大事にしてください。", "照顧好自己！"),
    ("元気でね。", "保重！"),
    ("幸運を。", "祝你好運！"),
    ("愛しています。", "我愛你。"),
    ("あなたは美しいです。", "你很漂亮。"),
    ("あなたは非常に賢いです。", "你很聰明。"),
    ("あなたはとても親切です。", "你很好。"),
    ("あなたは非常にユーモアがあります。", "你很有趣。"),
    ("あなたが好きです。", "我喜歡你。"),
    ("あなたが可哀想です。", "我為你難過。"),
    ("あなたをいつくしみます。", "我為你感到驕傲。"),
    ("私はあなたを信頼しています。", "我信任你。"),
    ("あなたは私を信頼できます。", "你可以信任我。"),
    ("それは秘密です。", "那是個秘密。"),
    ("ごめんなさい。それは言えません。", "對不起，我不能告訴你。"),
    ("本当の事を言ってください。", "告訴我真相。"),
    ("私に嘘をつかないで。", "別騙我。"),
    ("それはあなたの責任です。", "那是你的錯。"),
    ("それは私の責任ではありません。", "那不是我的錯。"),
    ("申し訳ございません。申し訳ありません。", "對不起，我很抱歉。"),
    ("大丈夫です。問題ありません。", "沒關係，沒問題。"),
    ("あなたを許します。", "我原諒你。"),
    ("あなたを許すことができません。", "我不能原諒你。"),
    ("私たちは話す必要があります。", "我們需要談話。"),
    ("私は怒っています。", "我生氣了。"),
    ("私は悲しいです。", "我難過。"),
    ("私は幸せです。", "我很高興。"),
    ("私は神経質です。", "我很緊張。"),
    ("私は怖いです。", "我害怕。"),
    ("私は勇敢です。", "我很勇敢。"),
    ("私は陽気です。", "我很快樂。"),
    ("私は落ち込んでいます。", "我很沮喪。"),
    ("私は混乱しています。", "我很困惑。"),
    ("私は驚きました。", "我很驚訝。"),
    ("私は失望しています。", "我很失望。"),
    ("私は好奇心があります。", "我很好奇。"),
    ("私は喜んでいます。", "我很愉快。"),
    ("私はいらいらしています。", "我很煩。"),
    ("それは素晴らしい。", "那太棒了！"),
    ("それは恐ろしい。", "那太可怕了！"),
    ("それは素晴らしい。", "那太棒了！"),
    ("それは素晴らしい。", "那太美妙了！"),
    ("それは優秀です。", "那很優秀！"),
    ("それはOK。", "那還可以。"),
    ("それはそこそこです。", "那一般般。"),
    ("それは中程度です。", "那還算中等。"),
    ("それは良くありません。", "那不好。"),
    ("それはひどいです。", "那太糟糕了。"),
]

# 生成題目
def generate_questions(data):
    questions = []
    wrong_answers_list = [
        ["不是這個意思。", "完全不同。", "錯誤翻譯。"],
        ["這是另一個句子。", "這個翻譯不對。", "不對的。"],
        ["這個意思不同。", "並非如此。", "不同的表達。"],
        ["這不是這個意思。", "錯誤的。", "不同意思。"],
        ["這個翻譯錯了。", "這不對。", "完全不同的。"],
    ]
    
    for idx, (original, correct) in enumerate(data):
        # 為每個題目添加多個變化以達到1000+題
        for variation in range(3):  # 每個題目做3個變化
            wrong_idx = (idx + variation) % len(wrong_answers_list)
            wrong_answers = wrong_answers_list[wrong_idx]
            
            questions.append({
                "text": original,
                "choices": [correct] + wrong_answers[:2],
                "answer": 0
            })
    
    return questions

german_questions = generate_questions(german_data)
japanese_questions = generate_questions(japanese_data)

# 輸出結果
print(f"德文題目數量: {len(german_questions)}")
print(f"日文題目數量: {len(japanese_questions)}")

# 生成JavaScript代碼
german_js = "const germanQuestions = " + json.dumps(german_questions, ensure_ascii=False) + ";"
japanese_js = "const japaneseQuestions = " + json.dumps(japanese_questions, ensure_ascii=False) + ";"

# 保存到文件
with open("questions_output.js", "w", encoding="utf-8") as f:
    f.write(german_js)
    f.write("\n\n")
    f.write(japanese_js)

print("題目已保存到 questions_output.js")
